apiVersion: apps/v1
kind: Deployment
metadata:
  name: "risk-tribe"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "risk-tribe"
  template:
    metadata:
      labels:
        app: "risk-tribe"
    spec:
      containers:
        - name: "risk-tribe"
          image: "risk-tribe:latest"
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
